<?php
namespace JaguarJack\CatchAdmin\Models;

use JaguarJack\CatchAdmin\Traits\Db\CurdTrait;
use JaguarJack\CatchAdmin\Traits\Db\RegisterBuilderMethodTrait;
use JaguarJack\CatchAdmin\Traits\Db\TrainsTrait;
use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
    use RegisterBuilderMethodTrait, TrainsTrait, CurdTrait;

    protected $limit = 10;

    /**
     * 转换 unix 时间戳
     *
     * @var string
     */
    protected $dateFormat = 'U';


   protected static function boot()
   {
       parent::boot(); // TODO: Change the autogenerated stub

       if (property_exists(static::class, 'observer')) {
           static::observe(static::$observer);
       }
   }
}
