<?php
namespace JaguarJack\CatchAdmin\Models;

use JaguarJack\CatchAdmin\Traits\Db\CurdTrait;
use JaguarJack\CatchAdmin\Traits\Db\RegisterBuilderMethodTrait;
use JaguarJack\CatchAdmin\Traits\Db\TrainsTrait;
use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
    use RegisterBuilderMethodTrait, TrainsTrait, CurdTrait;

    protected $limit = 10;

    /**
     * BaseModel constructor.
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    /**
     * boot
     *
     * @time 2019年09月26日
     * @return void
     */
    protected static function boot()
    {
       parent::boot(); // TODO: Change the autogenerated stub

       if (property_exists(static::class, 'observer')) {
           static::observe(static::$observer);
       }
    }


    protected function initModelAttribute()
    {
        $modelSetting = config('catchAdmin');

        /**
         * unix 时间戳设置
         */
        if ($modelSetting['unix_timestamp']) {
            $this->dateFormat = 'U';
        }

        /**
         * 分页设置
         */
        $this->limit = $modelSetting['page_limit'];
    }
}
